# Generated by Django 5.0.3 on 2024-03-05 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('people_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('registered_at', models.DateTimeField(default=datetime.datetime(2024, 3, 5, 21, 21, 9, 888776))),
            ],
        ),
    ]
